AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  testimport3:
    Type: 'AWS::Serverless::Function'
    DeletionPolicy: Retain
    Properties:
      FunctionName: testimport3
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: testimport3/
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::000000000000:role/service-role/testimport3-role-gec6wfo6'
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto